#! /usr/bin/env bash
installdir=/home/justalternate/.config/pywal-discord
themesdir=/home/justalternate/.config/pywal-discord

unameOut="$(uname -s)"
case "${unameOut}" in
    Darwin*)
        installdir=/home/justalternate/.config/pywal-discord
        themesdir=/home/justalternate/.config/pywal-discord-themes
        ;;
esac

mkdir -p "$themesdir"

if [ -e "$installdir" ]
then
	rm -rf "$installdir"
fi

mkdir "$installdir"
cp ./config/* "$installdir"
