{
  pkgs,
  inputs,
  ...
}:
{
  imports = [
    ./zsh.nix
    ./llm.nix
    ./fastfetch.nix
    inputs.sops-nix.homeManagerModules.sops
  ];

  home.packages = with pkgs; [
    ffmpeg
    bemoji
    marp-cli
    compose2nix
    lazygit
    openssh
    gcc
    lua
    go
    unstable.golangci-lint
    cmake
    gnumake
    opentofu
    awscli2
    devenv
    pre-commit
    gh
    bat
    gh-dash
    statix
    deadnix
    nixfmt-rfc-style
    kubectl
    kubernetes-helm
    k9s
    ani-cli
    vim
    inputs.justnixvim.packages.${pkgs.stdenv.hostPlatform.system}.default
    inputs.fleettui.packages.${pkgs.stdenv.hostPlatform.system}.default
  ];
}
