{
 "title": "Logs",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "unit",
    "label": "unit",
    "query": {}
   },
   { "name": "search", "label": "search" }
  ]
 },
 "panels": [
  {
   "title": "Error Rate %",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(count_over_time({host=\"beaver\", job=\"systemd-journal\", unit=~\"$unit\"}\n  | logfmt\n  | detected_level=~\"(?i)error|err|crit|critical|fatal\"[5m]))\n)\n/\n(\n  sum(count_over_time({host=\"beaver\", job=\"systemd-journal\", unit=~\"$unit\"}[5m]))\n)\n* 100",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "Logs/min",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({host=\"beaver\", job=\"systemd-journal\", unit=~\"$unit\"}[5m])) / 5",
     "legendFormat": "Logs/min"
    }
   ]
  },
  {
   "title": "Logs Count By Level",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n  count_over_time({host=\"beaver\", job=\"systemd-journal\", service_name=\"systemd-journal\", unit=~\"$unit\"}\n  | logfmt\n  | detected_level=~\"(?i)info|information|notice\"\n  |~ `(?i).*${search}.*` [$__interval])\n)",
     "legendFormat": "info"
    },
    {
     "direction": "backward",
     "expr": "sum(\n  count_over_time({host=\"beaver\", job=\"systemd-journal\", service_name=\"systemd-journal\", unit=~\"$unit\"}\n  | logfmt\n  | detected_level=~\"(?i)err|error|crit|critical|fatal\"\n  |~ `(?i).*${search}.*` [$__interval])\n)",
     "legendFormat": "error"
    },
    {
     "direction": "backward",
     "expr": "sum(\n  count_over_time({host=\"beaver\", job=\"systemd-journal\", service_name=\"systemd-journal\", unit=~\"$unit\"}\n  | logfmt\n  | detected_level=~\"(?i)warn|warning\"\n  |~ `(?i).*${search}.*` [$__interval])\n)",
     "legendFormat": "warn"
    }
   ]
  },
  {
   "title": "All Errors and Warn Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{host=\"beaver\", job=\"systemd-journal\", service_name=\"systemd-journal\", unit=~\"$unit\"} | logfmt | label_format level=detected_level | level =~ `error|warn` |~ `(?i).*${search}.*`"
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{host=\"beaver\", job=\"systemd-journal\", service_name=\"systemd-journal\", unit=~\"$unit\"} | logfmt |~ `(?i).*${search}.*`"
    }
   ]
  }
 ]
}